### ISSUE TITLE
Pacchetto per diagrammi commutativi

### ISSUE THREAD

**Issue by auron95** [snsmathlessons/Zannier1617#38]
Ciao,

potrebbe essere utile inserire un pacchetto per disegnare diagrammi commutativi (sempre che non sia già presente, nel caso mi scuso). In particolare a me servirebbe per l'ultima lezione in cui ci sono sollevamenti di applicazioni ogni due parole.

Per fare un esempio, io normalmente usavo il pacchetto `diagrams`. È possibile aggiungerlo?

**Comment by trenta3** [comment]
Certamente! `diagrams` è anche il mio preferito. Se vuoi puoi aggiungerlo tu stesso includendo il file, altrimenti dovrebbe arrivare con l'aggiunta della lezione di @frame95 (visto che anche lui ne aveva bisogno, se non ricordo male)

**Comment by trenta3** [comment]
diagrams.sty aggiunto
