### ISSUE TITLE
Osservazioni e linee guida sul lavoro svolto

### ISSUE THREAD

**Issue by trenta3** [snsmathlessons/Zannier1617#5]
@ilcusu @frame95 che vi pare di questa idea? Non so se avete già letto il README ed un po' di pagine collegate. Avete suggerimenti / migliorie da proporre?

**Comment by frame95** [comment]
Ehi Balbo, ma è fichissimo!

Non mi ero accorto di tutti i file che avevi inserito: solitamente vengono
listati nella pagina principale del repository. Da quello che ho capito
però snsmathlessons è un'organizzazione; sarà quello.

Ho letto tutto. Non sono certo di aver capito per bene come si lavorerà a
regime, ma mi pare che siano i tipici dubbi delle cose che sono più facili
a farsi che a dirsi (come lavorare con un repository). Aspetterei perciò di
lavorarci prima di chiedere.

Ho visto invece un index.md e dei css; hai per caso intenzione di fare un
sito?

Grazie per il tempo che ci hai dedicato, gran bel lavoro! Per come è
adesso, mi sembra possa funzionare bene; magari ci sono delle cose che
noteremo solo nella pratica e avremo il tempo di curarcene.

Bella,
Andrea

Il 18/ago/2016 11:53, "Dario Balboni" notifications@github.com ha scritto:

**Comment by ilcusu** [comment]
Ciao, scusa, ma in questo momento non sono in Italia, quindi non ho ancora
avuto il tempo di guardare tutto, appena sono a casa ti faccio sapere

Il 18/ago/2016 12:16, "frame95" notifications@github.com ha scritto:

**Comment by trenta3** [comment]
@frame95 Si, c'è un sito che contiene il pdf compilato: [È questo](http://zannier1617.surge.sh).
Il repository funziona che ad ogni aggiornamento del branch `master` parte un lavoro di compilazione dei sorgenti presenti nel repository e ne viene fatto l'upload su quel sito.

Spero che si riesca davvero ad usare per come ho messo giù le cose. Vedremo. In realtà non so nemmeno se quelli del terzo anno abbiano già fatto tutto il lavoro e quindi non ce ne sia troppo bisogno, ma mi è stato riferito che il corso cambia argomenti abbastanza spesso.

@ilcusu Non ti preoccupare, goditi la vacanza (spero).

**Comment by frame95** [comment]
Ahahahahah che taglio, ho appena letto il pdf. Leggo delle note di umorismo
tra le righe della serietà.

Il 18/ago/2016 15:38, "Dario Balboni" notifications@github.com ha scritto:
