### ISSUE TITLE
Scrittura Lezione 23 Gennaio 2017

### ISSUE THREAD

**Issue by trenta3** [snsmathlessons/Zannier1617#55]
Ci siamo di nuovo...

**Comment by frame95** [comment]
hai rotto il cazzo dario

Il 06/feb/2017 16:36, "Dario Balboni" <notifications@github.com> ha scritto:

**Comment by frame95** [comment]
Ora questo mese ti requisisco la mail

Il 06/feb/2017 17:11, "Andrea Marino" <andrea.marino@sns.it> ha scritto:

**Comment by trenta3** [comment]
Potresti anche finire la tua lezione e/o disiscriverti dalle notifiche
